# Generated by Django 3.1 on 2020-08-16 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_to_Mob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interested_mobilizers', models.ManyToManyField(blank=True, related_name='_task_to_mob_interested_mobilizers_+', to=settings.AUTH_USER_MODEL)),
                ('select_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
