# Generated by Django 3.1 on 2020-08-16 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_task_to_mob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_to_mob',
            name='select_task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.task'),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1500)),
                ('completed_status', models.IntegerField(default=0)),
                ('mobilizer_submitted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task_selected_by_mob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.task')),
            ],
        ),
    ]
